# Generated by Django 5.0.4 on 2024-04-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0002_vacancy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='VacancyDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
