# Generated by Django 5.0.4 on 2024-04-23 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0003_alter_vacancy_vacancydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='VacancyStatus',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='working.vacancystatus'),
        ),
    ]
