# Generated by Django 5.0.4 on 2024-04-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0004_alter_vacancy_vacancystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='user',
            new_name='userId',
        ),
    ]
