# Generated by Django 5.0.4 on 2024-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0005_rename_user_vacancy_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
