# Generated by Django 5.0.4 on 2024-04-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0007_vacancy_vacancyusename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='VacancyUsename',
            new_name='VacancyUsername',
        ),
    ]
