# Generated by Django 5.0.4 on 2024-04-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0009_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='VacancyRequirements',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
