# Generated by Django 5.0.4 on 2024-04-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0011_vacancy_vacancyconditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='Contacts',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
