# Generated by Django 5.0.4 on 2024-05-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0012_vacancy_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferences',
        ),
    ]
